server:
  addr: ":8080"
  cors_origins: ["http://localhost:5173"]
auth:
  secret: "a-string-secret-at-least-256-bits-long"
  access_ttl: 24h
  refresh_ttl: 1440h
postgres:
  host: chatter-postgres
  port: 5432
  username: postgres
  password: password
  database: postgres
  min_conns: 1
  max_conns: 100

redis:
  host: redis
  port: 6379
  username: default
  password: password
  db: 0
